### ISSUE TITLE
Adding Relationships causes duplication of effort

### ISSUE THREAD

**Issue by teleclimber** [mfcochauxlaberge/jsonapi#110]
Bonjour 👋,

Thanks for this library.

I am playing with creating a schema and it seems like I have to add relationships twice for `schema.Check()` to be happy.

For example you have this in /examples/schema_test.go:

```
//...
comments.AddRel(jsonapi.Rel{
		FromType: "comments",
		FromName: "author",
		ToOne:    true,
		ToType:   "users",
		ToName:   "comments",
		FromOne:  false,
	})

// ....

schema.AddRel("users", jsonapi.Rel{
		FromType: "users",
		FromName: "comments",
		ToOne:    false,
		ToType:   "comments",
		ToName:   "author",
		FromOne:  true,
	})

```

It seems the `Rel` fully describes a bidirectional relationship, but I have to add it twice, once for each side. If I don't add the mirror `Rel` then `schema.Check()` complains that relationship x of type y and its inverse do not point each other.

If I am building a large schema that's a lot of manual labor to create all relationships. Could this be streamlined, or am I missing something?

I am kind of new to the JSON:API spec so I may be missing something there too.

Merci!

**Comment by mfcochauxlaberge** [comment]
Hey, thanks for writing this issue.

When the first relationship is provided, it contains all the information necessary to calculate the opposite way. So yeah, this is definitely a good idea and it would be a decent improvement.

I'll try a quick implementation and see how the test suite behaves.

**Comment by mfcochauxlaberge** [comment]
The main problem I have right now is that sometimes you add a relationship, but the target type isn't part of the schema yet.

I could try to add the inverse way anyway and just not do it if the type does not exist yet, but I'm afraid that the behaviour would now contain to much magic.

I'll have to think about it more.

**Comment by teleclimber** [comment]
You could add a new method `AddBidiRel` that adds both  and fails if the other type is missing? You could leave `AddRel` untouched for those times when someone wants to add relationships before the other type is present.

**Comment by mfcochauxlaberge** [comment]
@teleclimber Haha, that's exactly what I had in mind. I just created a PR. Let me know your feedback.

**Comment by teleclimber** [comment]
Tried it locally on my project and yeah, that's just what's needed. 👍

**Comment by mfcochauxlaberge** [comment]
Merged. It will be part of the next release, which should arrive soon.
