### ISSUE TITLE
Meta field in data field

### ISSUE THREAD

**Issue by lluuvr** [mfcochauxlaberge/jsonapi#97]
Hey. Can I include meta field in data field? I only found information how to include meta in top-level object.
Example:
```
{
  "data": {
    "type": "ecostructures",
    "id": "1YzLGq1SNPSO072rk07CfyLTdd1",
    "meta": {
      "revision": "7219f50892fd94207dda27dc038460fabd0b90c9b4aa4d9e8d5581513e1c01f0"
    }
  }
}
```

**Comment by mfcochauxlaberge** [comment]
Ah! No, you currently can't. But the spec allows it, so this library should too.

**Comment by mfcochauxlaberge** [comment]
I started a PR.

To be clear, the meta field is being added to resource objects, not the data object.

**Comment by lluuvr** [comment]
Thank you for the fast help 🙂.

**Comment by mfcochauxlaberge** [comment]
Hi, the feature is implemented on master. It will be part of the next version. Feel free to open another ticket if there's a bug, something missing, or anything else.

**Comment by lluuvr** [comment]
Thank you.
